# Laboratorio #3
### Análisis de Datos con Python
> *Estudiante: Víctor Manuel Rodríguez Umaña*

> *Carnet: 24007670*

> *Curso: Ciencia de Datos en Python*

## Parte 1: Numpy

In [1]:
import numpy as np

### Ejercicio 1
¿Cuál es el tamaño en bytes de un array de 1000 elementos de tipo booleano?

In [4]:
booleanos = np.zeros(1000, dtype='bool')
booleanos.nbytes

1000

### Ejercicio 2
Cree un array cuyos elementos sean los enteros pares en [1,100] y en orden decreciente. Muestre los 10 últimos por pantalla.

In [7]:
pares = np.arange(100, 1, -2)
print(pares[-10:])

[20 18 16 14 12 10  8  6  4  2]


### Ejercicio 3
Dado el array  
    2  4  5  6     
    0  3  7  4      
    8  8  5  2      
    1  5  6  1  
Seleccione con una instrucción el subarray de elementos  
    0  3  7  4  
Después, seleccione el subarray de elementos  
    2  5  
    8  5

In [14]:
x = np.array([[[2,4,5,6],
               [0,3,7,4]],
              [[8,8,5,2],
               [1,5,6,1,]]
             ])

In [15]:
x[0,1]

array([0, 3, 7, 4])

In [23]:
[[x[0,0,0], x[0,0,2]], [x[1,0,0], x[1,0,2]]]

[[2, 5], [8, 5]]

### Ejercicio 4
Dados los arrays a = [1, 4, 2, 7] y b = [1, 3, 2, 9], obtenga la media aritmética de la diferencia (a-b).

In [25]:
a = np.array([1, 4, 2, 7])
b = np.array([1, 3, 2, 9])
np.mean(a-b)

-0.25

### Ejercicio 5
Tengo valores de cordenadas (x, y) en las columnas del array  
    1.33 4.5  
    30.0 10.7  
    70.2 0.5  
    Agregue a este array las coordenadas (37.1, -3.6). Muestre en pantalla las dimensiones del nuevo array.

In [58]:
coordenadas = np.array([[1.33, 4.5],
                        [30.0, 10.7],
                        [70.2, 0.5]
                       ])
coordenadas = np.vstack((coordenadas, [37.1, -3.6]))
coordenadas

array([[ 1.33,  4.5 ],
       [30.  , 10.7 ],
       [70.2 ,  0.5 ],
       [37.1 , -3.6 ]])

In [59]:
coordenadas.shape

(4, 2)

### Ejercicio 6.
Copie el array del ejercicio anterior. Traspóngalo.Agregue ahora dos nuevos pares de coordenadas: (10.8, 3.0) y (35.8, 12.0).

In [64]:
transpuesto = np.transpose(coordenadas)
transpuesto

array([[ 1.33, 30.  , 70.2 , 37.1 ],
       [ 4.5 , 10.7 ,  0.5 , -3.6 ]])

In [65]:
transpuesto = np.vstack((coordenadas, [10.8, 3.0]))
transpuesto = np.vstack((coordenadas, [35.8, 12.0]))
transpuesto

array([[ 1.33,  4.5 ],
       [30.  , 10.7 ],
       [70.2 ,  0.5 ],
       [37.1 , -3.6 ],
       [35.8 , 12.  ]])

## Parte 2: Exploración y minería de datos

In [67]:
import pandas as pd

In [70]:
dataset = pd.read_csv("NucleosPoblacion.csv")
dataset.head()

FID  OBJECTID     Texto  Poblacion  CodMun Municipio  CodProvin  \
0    0         1   Agüimes    29431.0   35002   Agüimes         35   
1    1         2   Antigua    10458.0   35003   Antigua         35   
2    2         3  Arrecife    58156.0   35004  Arrecife         35   
3    3         4    Arucas    36745.0   35006    Arucas         35   
4    4         5    Gáldar    24473.0   35009    Gáldar         35   

    Provincia          X          Y  
0  Las Palmas -15.446012  27.900542  
1  Las Palmas -14.013301  28.418966  
2  Las Palmas -13.551451  28.960649  
3  Las Palmas -15.521512  28.117496  
4  Las Palmas -15.654111  28.143873